import Head from 'next/head'
import { Text, Container } from "@nextui-org/react";

import { useTheme as useNextTheme } from 'next-themes'
import { Switch, useTheme } from '@nextui-org/react'

export default function Home() {
    const { setTheme } = useNextTheme();
    const { isDark, type } = useTheme();

    return (
        <>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <Container>
                <Text h2>The current theme is: {type}</Text>   
                <Switch
                    checked={isDark}
                    onChange={(e) => setTheme(e.target.checked ? 'dark' : 'light')}
                />
            </Container>
        </>
    )
}
